/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chessgui;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;

import javax.swing.ImageIcon;

import chessgui.learn.endgame;
import chessgui.learn.introduction;
import chessgui.learn.learnFrame;
import chessgui.learn.middlegame;
import chessgui.learn.opening;
import chessgui.puzzle.puzzleFrame;
/**
 *
 * @author ASUS
 */
public class mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form mainmenu
     */
    Component component;
    public mainmenu() {
        
        
        initComponents();
        setSize (740, 650);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

       

            jPanel6 = new javax.swing.JPanel();
            panelUtama = new javax.swing.JPanel();
            panelMenu = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            buttonPlay = new javax.swing.JButton();
            buttonLearn = new javax.swing.JButton();
            buttonPuzzle = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            panelPlay = new javax.swing.JPanel();
            panelLearn = new javax.swing.JPanel();
            jPanel4 = new javax.swing.JPanel();
            EndLabel = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            OpeningLabel = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            middleLabel = new javax.swing.JLabel();
            jPanel7 = new javax.swing.JPanel();
            IntroductionLabel = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            panelPuzzle = new javax.swing.JPanel();
    
            jPanel6.setBackground(new java.awt.Color(204, 0, 0));
    
            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 620, Short.MAX_VALUE)
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 110, Short.MAX_VALUE)
            );
    
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(null);
    
            panelUtama.setLayout(new java.awt.CardLayout());
    
            buttonPlay.setText("Play");
            buttonPlay.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonPlayActionPerformed(evt);
                }
            });
    
            buttonLearn.setText("Learn");
            buttonLearn.setToolTipText("");
            buttonLearn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonLearnActionPerformed(evt);
                }
            });
    
            buttonPuzzle.setText("Puzzle");
            buttonPuzzle.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonPuzzleActionPerformed(evt);
                }
            });
    
            jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("CATUR");
    
            javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
            panelMenu.setLayout(panelMenuLayout);
            panelMenuLayout.setHorizontalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                            .addGap(272, 272, 272)
                            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonPuzzle, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(buttonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(buttonLearn, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                        .addGroup(panelMenuLayout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panelMenuLayout.setVerticalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(buttonLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(buttonPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22))
            );

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("header.jpeg")));
            panelUtama.add(panelMenu, "card2");
    
            javax.swing.GroupLayout panelPlayLayout = new javax.swing.GroupLayout(panelPlay);
            panelPlay.setLayout(panelPlayLayout);
            panelPlayLayout.setHorizontalGroup(
                panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            panelPlayLayout.setVerticalGroup(
                panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
    
            panelUtama.add(panelPlay, "card3");
    
            panelLearn.setLayout(null);
    
            jPanel4.setBackground(new java.awt.Color(204, 0, 0));
            jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel4MouseClicked(evt);
                }
            });
    
            EndLabel.setText("End Game");
    
            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(171, Short.MAX_VALUE)
                    .addComponent(EndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(EndLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap())
            );
    
            panelLearn.add(jPanel4);
            jPanel4.setBounds(60, 450, 620, 110);
    
            jPanel3.setBackground(new java.awt.Color(204, 0, 0));
            jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel3MouseClicked(evt);
                }
            });
    
            OpeningLabel.setText("Opening Move");
    
            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(173, Short.MAX_VALUE)
                    .addComponent(OpeningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OpeningLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            );
    
            panelLearn.add(jPanel3);
            jPanel3.setBounds(60, 180, 620, 110);
    
            jPanel5.setBackground(new java.awt.Color(204, 0, 0));
            jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel5MouseClicked(evt);
                }
            });
    
            middleLabel.setText("Middle Game");
    
            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(171, Short.MAX_VALUE)
                    .addComponent(middleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(middleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap())
            );
    
            panelLearn.add(jPanel5);
            jPanel5.setBounds(60, 320, 620, 110);
    
            jPanel7.setBackground(new java.awt.Color(204, 0, 0));
            jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel7MouseClicked(evt);
                }
            });
    
            IntroductionLabel.setText("Piece Introduction");
    
            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(171, Short.MAX_VALUE)
                    .addComponent(IntroductionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12))
            );
            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(IntroductionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap())
            );
    
            panelLearn.add(jPanel7);
            jPanel7.setBounds(60, 50, 620, 110);
    
          
            panelLearn.add(jLabel7);
            jLabel7.setBounds(0, 0, 50, 40);
            jLabel7.setText("Back");
            jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    BackMouseClicked(evt);
                }
            });
          
           
    
            panelUtama.add(panelLearn, "card4");
    
            javax.swing.GroupLayout panelPuzzleLayout = new javax.swing.GroupLayout(panelPuzzle);
            panelPuzzle.setLayout(panelPuzzleLayout);
            panelPuzzleLayout.setHorizontalGroup(
                panelPuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            panelPuzzleLayout.setVerticalGroup(
                panelPuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
    
            panelUtama.add(panelPuzzle, "card5");
    
            getContentPane().add(panelUtama);
            panelUtama.setBounds(0, 0, 730, 590);
    
            pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
            this.setVisible(false);
            new BoardFrame().setVisible(true);
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLearnActionPerformed
            panelUtama.removeAll();
            panelUtama.add(panelLearn);
            panelUtama.repaint();
            panelUtama.revalidate();        
    }//GEN-LAST:event_buttonLearnActionPerformed

    private void buttonPuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPuzzleActionPerformed
        this.setVisible(false);
        new puzzleFrame().setVisible(true);
    }//GEN-LAST:event_buttonPuzzleActionPerformed

    
    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        this.setVisible(false);
        new learnFrame().setVisible(true);
        new introduction().setVisible(true);
     
    }                                    

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        this.setVisible(false);
        new opening().setVisible(true);
    }                                    

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        this.setVisible(false);
        new middlegame().setVisible(true);
    }                                    

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        this.setVisible(false);
        new endgame().setVisible(true);
    }                    

    
    private void BackMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.add(panelMenu);
        panelUtama.repaint();
        panelUtama.revalidate();  
    }       
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLearn;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonPuzzle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel OpeningLabel;
    private javax.swing.JLabel middleLabel;
    private javax.swing.JLabel IntroductionLabel;
    private javax.swing.JLabel EndLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelLearn;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPlay;
    private javax.swing.JPanel panelPuzzle;
    // End of variables declaration//GEN-END:variables
}
